---
- name: Install neovim - Debian
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - neovim
      - python3-neovim
  when: ansible_os_family == 'Debian'

- name: Install neovim - RedHat
  ansible.builtin.dnf:
    update_cache: yes
    name:
      - neovim
      - python3-neovim
  when: ansible_os_family == 'RedHat'

- name: Create directory path for Vim-Plug
  become: false
  ansible.builtin.file:
    path: /home/{{ system_user }}/.local/share/nvim/site/autoload
    state: directory

- name: Download Vim-Plug installer
  become: false
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ system_user }}/.local/share/nvim/site/autoload/plug.vim
    mode: 0755
