---
- name: Apt
  block:
    - name: Update, upgrade, autoclean, and autoremove apt packages
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
        autoremove: yes
        autoclean: yes

    - name: Install apt packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - curl
          - apt-transport-https
          - ca-certificates
          - fzf
          - bat
          - silversearcher-ag
          - git
          - python3
          - python3-pip
          - tmux
        state: present

    - name: Install Google Chrome
      ansible.builtin.apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Install Zoom
      ansible.builtin.apt:
        deb: https://zoom.us/client/latest/zoom_amd64.deb

- name: Snaps
  block:
    - name: Install node
      community.general.snap:
        name: node
        state: present
        classic: yes

    - name: Install postman
      community.general.snap:
        name: postman
        state: present

    - name: Install gimp
      community.general.snap:
        name: gimp
        state: present

    - name: Install powershell
      community.general.snap:
        name: powershell
        state: present
        classic: yes

    - name: Install vscode
      community.general.snap:
        name: code
        state: present
        classic: yes

    - name: Install spotify
      community.general.snap:
        name: spotify
        state: present

    - name: Install discord
      community.general.snap:
        name: discord
        state: present

    - name: Install slack
      community.general.snap:
        name: slack
        state: present

    - name: Install remmina
      community.general.snap:
        name: remmina
        state: present

- name: Kubectl
  block:
    - name: Add kubectl apt repository key
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Add kubectl apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        filename: kubectl

    - name: Install kubectl
      ansible.builtin.apt:
        name: kubectl
