---
- name: Apt
  block:
    - name: Update, upgrade, autoclean, and autoremove apt packages
      ansible.builtin.apt:
        upgrade: full
        update_cache: yes
        autoremove: yes
        autoclean: yes

    - name: Install apt packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - curl
          - apt-transport-https
          - ca-certificates
          - fzf
          - bat
          - silversearcher-ag
          - git
          - python3
          - python3-pip
          - tmux
        state: present
