---
- name: dnf
  block:
    - name: Autoremove dependencies
      ansible.builtin.dnf:
        autoremove: yes

    - name: Upgrade all packages
      ansible.builtin.dnf:
        update_cache: yes
        name: "*"
        state: latest

    - name: Install dnf packages
      ansible.builtin.dnf:
        update_cache: yes
        name:
          - curl
          - fzf
          - bat
          - the_silver_searcher
          - git
          - python3
          - python3-pip
          - tmux
          - fedora-workstation-repositories
          - nodejs
          - gimp
          - flatpak
        state: latest
